version: '3.7'

# docker-compose override for development
services:
  backend:
    build:
      dockerfile: dev.dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9223
    command: npm run start:debug
  frontend:
    build:
      target: development
    ports:
      - ${FRONTEND_PORT}:4200
    command: npm run start
  postgres:
    ports:
      - ${DB_PORT}:5432
  