version: '3.7'

# docker-compose override for production
services:
  backend:
    build:
      dockerfile: prod.dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
  frontend:
    build:
      target: production
    ports:
      - ${FRONTEND_PORT}:80