version: '3.7'

# docker-compose override for development
services:
  backend:
    build:
      target: development
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    command: npm run start:debug
  frontend:
    build:
      target: development
    ports:
      - ${FRONTEND_PORT}:4200
    command: npm run start
  